### ISSUE TITLE
Use only lower-case for `installInfo` filename

### ISSUE THREAD

**Issue by aaaaalbert** [SeattleTestbed/installer-packaging#4]
`seattleinstaller.py` creates a file `installInfo.old` (or `.new`) in the servicevessel directory where it stores results of the system benchmark, donated percentage, and amount of resources that will be used by Seattle. However, on installs running a V2 nodemanager, files in vessels can only be accessed if their names have lower-case characters ([and a few other things](https://github.com/SeattleTestbed/repy_v2/blob/master/emulfile.py#L46-L47)) exclusively. As a result, you cannot retrieve or otherwise manipulate `installInfo` via seash (see below).

This issue is RepyV2-specific. RepyV1 files may contain upper-case characters. We need to be able to see the information contained in the file for debugging purposes on any version of Seattle, so let's make the base filename `installinfo` (all lower-case) instead.

This requires changes in anything that depends on this exact file name:
- Seattle Installer, https://github.com/SeattleTestbed/installer-packaging/blob/master/all-platforms/seattleinstaller.py#L2146
- Seattle Uninstaller, https://github.com/SeattleTestbed/installer-packaging/blob/master/all-platforms/seattleuninstaller.py#L604
- Android app (1), https://github.com/SensibilityTestbed/sensibility-testbed/blob/e2907df340ec08f6d6c12b241b65bf7de28679b0/SensibilityTestbed/src/com/sensibility_testbed/InstallerService.java#L125-L133
- Android app (2), https://github.com/SensibilityTestbed/sensibility-testbed/blob/359dc6b17ec4d0d8734d86b0f71ce033a0d05412/SensibilityTestbed/src/com/sensibility_testbed/ScriptActivity.java#L311

---

seash log:

```
servicevessel@%1 !> cat installInfo.old
An error occurred: Node Manager error 'Filename has disallowed character 'I''
Affected vessels: ee7eb6c1bb4389a62812a9c47b76a0c5f47b0b3e:1224:v9.
servicevessel@%1 !> download installInfo.old
An error occurred: Node Manager error 'Filename has disallowed character 'I''
Affected vessels: ee7eb6c1bb4389a62812a9c47b76a0c5f47b0b3e:1224:v9.
servicevessel@%1 !> delete installInfo.old
An error occurred: Node Manager error 'Filename has disallowed character 'I''
Affected vessels: ee7eb6c1bb4389a62812a9c47b76a0c5f47b0b3e:1224:v9.
```

**Comment by JustinCappos** [comment]
Should be an easy fix.  Let's do it.
